helmDefaults:
  wait: false
  atomic: true
  timeout: 600

environments:
  default:
    values:
      - values/.env-default.yaml

---

releases:
  {{- range $serviceName, $serviceConfig := .Environment.Values.services }}
  - name: {{ $serviceName }}
    namespace: dev
    chart: ./charts/golang-dev
    # {{- if hasKey $serviceConfig "dependencies" }}
    # needs:
    #   {{- range $dep := $serviceConfig.dependencies }}
    #   - {{ $dep }}
    #   {{- end }}
    # {{- end }}
    values:
      - nameOverride: {{ $serviceName }}
      - service:
          port: {{ $serviceConfig.port }}
      {{- if hasKey $serviceConfig "cmd" }}
        cmd: |-
          {{- $serviceConfig.cmd | nindent 10 }}
      {{- end }}
      {{- if hasKey $serviceConfig "ingress" }}
      - ingress:
          enabled: true
          hosts:
            - host: {{ $serviceName }}.local
              paths:
                - path: /
                  pathType: Prefix
      {{- end }}
      {{- if hasKey $serviceConfig "volumes" }}
      - volumes:
        {{- toYaml $serviceConfig.volumes | nindent 8 }}
      {{- end }}
      {{- if hasKey $serviceConfig "volumeMounts" }}
      - volumeMounts:
        {{- toYaml $serviceConfig.volumeMounts | nindent 8 }}
      {{- end }}
      {{- $hostAliases := list }}
      {{- if $.Environment.Values.hostAliases }}
        {{- $hostAliases = $.Environment.Values.hostAliases }}
      {{- end }}
      {{- if hasKey $serviceConfig "hostAliases" }}
        {{- $hostAliases = concat $hostAliases $serviceConfig.hostAliases }}
      {{- end }}
      {{- if $hostAliases }}
      - hostAliases:
        {{- toYaml $hostAliases | nindent 8 }}
      {{- end }}
      {{- if hasKey $serviceConfig "dependencies" }}
      - serviceDependencies:
          {{- range $dep := $serviceConfig.dependencies }}
          {{- if eq $dep "etcd" }}
          etcd: "etcd:2379"
          {{- else }}
          {{- $depConfig := index $.Environment.Values.services $dep }}
          {{ $dep }}: "{{ $dep }}:{{ $depConfig.port }}"
          {{- end }}
          {{- end }}
      {{- end }}
  {{- end }}
