apiVersion: v1
kind: Service
metadata:
  name: {{ include "golang-dev.fullname" . }}
  labels:
    {{- include "golang-dev.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 40000
      targetPort: debug
      protocol: TCP
      name: debug
  selector:
    {{- include "golang-dev.selectorLabels" . | nindent 4 }}
